widgets:
    -
        type: toc
        position: left
        index: true
        collapsed: true
        depth: 3
    -
        type: recent_posts
        position: left
    -
        type: categories
        position: left
    -
        type: tags
        position: left
        order_by: name
        amount: 15
        show_count: true