version: 5.1.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name:
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    structured_data:
        title: 梦鱼乡
        description: 个人博客
        url: https://github.com/imaginefish/blog
        author: 梦鱼
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/imaginefish/blog
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true

sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: 梦鱼
        author_title: 大数据开发工程师
        location: 中国.上海
        avatar: /img/avatar.jpg
        avatar_rounded: true
        gravatar:
        follow_link: https://github.com/imaginefish
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/imaginefish
            Email:
                icon: fas fa-envelope
                url: mailto:imaginefishes@outlook.com
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Hexo: https://hexo.io
            Icarus: https://ppoffice.github.io/hexo-theme-icarus
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
    -
        position: left
        type: archives
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true

plugins:
    animejs: true
    back_to_top: true
    busuanzi: true
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    katex: true
    mathjax: true
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome